### ISSUE TITLE
Macros are treated as undefined + configuring racer for code completion

### ISSUE THREAD

**Issue by rohitjoshi** [drrb/rust-netbeans#11]
First of all, thank you for creating Rust plugin for my favorite IDE Netbeans.
1. I have logging macros like debug! and info! which are shown as undefined.  
2. Code completion doesn't seem to work out of the box.  How do I configure racer path?

**Comment by drrb** [comment]
Thanks for raising this issue. Code completion is currently unsupported, though I'm hoping to add it in the future.

Regarding your macros, do they work when you run "cargo build" from the command line? What operating system are you using?
