### ISSUE TITLE
issue installing plugin ubuntu 14.04 x64, Netbeans 8.0.2 -- mvn package error

### ISSUE THREAD

**Issue by 00krishna** [drrb/rust-netbeans#14]
Hello. I was trying to install the plugin but ran into the following build errors when running mvn package.

[~/apps/rust-netbeans/]‹master› » mvn package
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Rust NetBeans Plugin 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (compile-build-addon) @ rust-netbeans ---
[INFO] Source directory: /home/krishnab/apps/rust-netbeans/src/build/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rust-netbeans ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 22 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ rust-netbeans ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:java (compile-rust-bridge) @ rust-netbeans ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
Changes detected. Compiling all Rust crates!
Compiling crate src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs
Running command: [rustc, --out-dir, target/rust-libs, src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs]
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:18:1: 18:25 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:18 #![feature(collections)]
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:19:1: 19:18 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:19 #![feature(core)]
                                                                ^~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:20:1: 20:18 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:20 #![feature(libc)]
                                                                ^~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:21:1: 21:22 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:21 #![feature(old_path)]
                                                                ^~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:22:1: 22:27 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:22 #![feature(rustc_private)]
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:23:1: 23:22 error: #[feature] may not be used on the stable release channel
src/main/rust/com/github/drrb/javarust/lib/javarustbridge.rs:23 #![feature(std_misc)]
                                                                ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to 6 previous errors
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: rustc exited nonzero (status code = 101)
    at com.github.drrb.rust.netbeans.build.CompileRustCrates.compile(CompileRustCrates.java:68)
    at com.github.drrb.rust.netbeans.build.CompileRustCrates.main(CompileRustCrates.java:49)
    ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.705s
[INFO] Finished at: Thu Sep 10 10:09:08 PDT 2015
[INFO] Final Memory: 14M/455M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (compile-rust-bridge) on project rust-netbeans: An exception occured while executing the Java class. null: InvocationTargetException: rustc exited nonzero (status code = 101) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Please let me know if you have any suggestions.

**Comment by Majora320** [comment]
You need to install [nightly rust](https://doc.rust-lang.org/book/nightly-rust.html).

**Comment by drrb** [comment]
Thanks for the report. I've had some time off working on this project, and Rust and NetBeans both moved on. I've started working on the plugin again, to fix it for the latest NetBeans and Rust versions. The plugin is buildable now, but needs some more work to get it working fully again.
