### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by mjfmechanic** [drrb/rust-netbeans#15]
I am quite new to installing plugins and maven all together but I attempted to build your plugin in netbeans however the following error ensued. I need RUST to compile a programming challenge but finding the right IDE or Editor plugin has been a bear.  Thanks in advance!

Mike

Error as follows:

Total time: 5.002s
Finished at: Wed Jun 29 18:27:41 PDT 2016
## Final Memory: 13M/207M

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (compile-rust-bridge) on project rust-netbeans: An exception occured while executing the Java class. null: InvocationTargetException: rustc exited nonzero (status code = 101) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

---

My system attributes:
Windows 8.1
Java VM 1.8.0_91
Netbeans 8.0.2 (with all available netbean maven plugins)
Rust 1.9 (w/cargo)

I attempted to install the maven plugin 1.3.2 from the repository as well and it builds fine but I get an error when executing the .jar file from the cmd window that there is no main manifest attribute. I don't know what's going on but today is definitely not my day with plugins.

-Mike

**Comment by drrb** [comment]
Thanks for the report. I've had some time off working on this project, and Rust and NetBeans both moved on. I've started working on the plugin again, to fix it for the latest NetBeans and Rust versions. The plugin is buildable now, but needs some more work to get it working fully again.
