### ISSUE TITLE
Doesn't package on OS X

### ISSUE THREAD

**Issue by francisl** [drrb/rust-netbeans#5]
on Master

mvn package failed with

    [INFO] --- antlr4-maven-plugin:4.0:antlr4 (default) @ rust-netbeans ---
    [INFO] ANTLR 4: Processing source directory /Volumes/HD2/Downloads/rust-netbeans/src/main/antlr4
    [INFO] Processing grammar: com/github/drrb/rust/netbeans/parsing/Rust.g4
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    ...
    [ERROR] Failed to execute goal org.antlr:antlr4-maven-plugin:4.0:antlr4 (default) on project rust-netbeans: Execution default of goal org.antlr:antlr4-maven-plugin:4.0:antlr4 failed: Index: 0, Size: 0 -> [Help 1]

**Comment by drrb** [comment]
Thanks for opening this issue. The old ANTLR-based parser has now been removed, so the project should now compile.
