### ISSUE TITLE
Fails to load native Rust libraries on Linux

### ISSUE THREAD

**Issue by drrb** [drrb/rust-netbeans#7]
Running the build on Linux currently yields segfaults during the tests (when JNA attempts to load our native component).

Example output: https://travis-ci.org/drrb/rust-netbeans/jobs/50808653#L2789.

**Comment by drrb** [comment]
Raised rust-lang/rust#22528.

**Comment by kordianbruck** [comment]
This would be great!

**Comment by azazar** [comment]
That bug seems fixed.

**Comment by drrb** [comment]
Thanks for following that up. I've started moving the plugin away from using the native Rust compiler now.
