### ISSUE TITLE
Test Case failures with Java 1.8 on mac

### ISSUE THREAD

**Issue by rohitjoshi** [drrb/rust-netbeans#8]
java -version
    java version "1.8.0"
    Java(TM) SE Runtime Environment (build 1.8.0-b132)
    Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

Failed tests:
  CargoConfigTest.shouldFindCratesForEachSource:41 Content does not match between 'crates/dependencies' and 'crates/dependencies.crates'
Expected content is:

crates:
    src/main.rs: EXECUTABLE
sources:
    src/orphan.rs:
        crate: src/orphan.rs
    src/main.rs:
        crate: src/main.rs
    src/other/mod.rs:
        crate: src/main.rs
    src/other/third.rs:
        crate: src/main.rs

but actual is:

crates:
    src/main.rs: EXECUTABLE
sources:
    src/orphan.rs:
        crate: src/orphan.rs
    src/main.rs:
        crate: src/main.rs
    src/other/third.rs:
        crate: src/main.rs
    src/other/mod.rs:
        crate: src/main.rs

It differs in the following things:

Line 7 contains different content than expected:
Expected: 	    src/other/mod.rs:
Actual:  	    src/other/third.rs:

Line 9 contains different content than expected:
Expected: 	    src/other/third.rs:
Actual:  	    src/other/mod.rs:

Tests run: 79, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
[INFO] Finished at: 2015-02-23T20:51:21-05:00
[INFO] Final Memory: 27M/1169M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project rust-netbeans: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/ytr289/projects/rust/rust-netbeans/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by drrb** [comment]
This should be fixed as of 1907cd6.
